config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"

  resources :jobs do
    resources :resumes
  end

  namespace :admin do

    resources :jobs do
        member do
          post :hide
          post :publish
        end

      resources :resumes

    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates :title, :description, presence: true
  validates :wage_lower_bound, numericality: { greater_than: 0 }
  validates :wage_upper_bound, presence: true
  validates :contact_email, presence: true
  has_many :resumes

  scope :recent, -> { order("created_at DESC") }

  def admin?
    is_admin
  end

  def hide!
    self.is_hidden = true
    self.save
  end

  def publish!
    self.is_hidden = false
    self.save
  end




end

app/models/resume.rb
class Resume < ApplicationRecord
  belongs_to :job
  belongs_to :user

  validates :content, presence: true

  mount_uploader :attachment, AttachmentUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


   def admin?
     is_admin
   end

   has_many :resumes


end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_is_admin
  layout "admin"

  def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to admin_jobs_path, notice: "Job created"
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to admin_jobs_path, notice: "Update"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
      redirect_to admin_jobs_path, alert: "Job Deleted"
  end

  def hide
    @job = Job.find(params[:id])
    @job.hide!
    redirect_to :back
  end

  def publish
    @job = Job.find(params[:id])
    @job.publish!
    redirect_to :back
  end






  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden )
  end




end

app/controllers/admin/resumes_controller.rb
class Admin::ResumesController < ApplicationController
  before_action :authenticate_user!
  before_action :require_is_admin

  layout 'admin'

  def index
    @job = Job.find(params[:job_id])
    @resumes = @job.resumes.order("created_at DESC")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def require_is_admin
    if !current_user.admin?
      redirect_to root_path, alert: "You are not admin!"
    end
  end


end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :edit, :destroy ]

  def index
    @jobs = case params[:order]
            when "by_lower_bound"
              Job.where(:is_hidden => false).order("wage_lower_bound DESC")
            when "by_upper_bound"
              Job.where(:is_hidden => false).order("wage_upper_bound DESC")
            else
              Job.where(:is_hidden => false).recent
            end
  end

  def show
    @job = Job.find(params[:id])

    if @job.is_hidden
      redirect_to root_path, alert: "Job is taken!"
    end
  end

  def new
    @job = Job.new
  end

  def edit
    @job = Job.find(params[:id])
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to jobs_path, notice: "Created"
    else
      render :new
    end
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      redirect_to jobs_path, notice: "Update Successful"
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
      redirect_to jobs_path, alert: "Delete Successful"
  end


  private

  def job_params
    params.require(:job).permit(:title, :description, :wage_lower_bound, :wage_upper_bound, :contact_email, :is_hidden )
  end

end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :authenticate_user!

  def new
    @job = Job.find(params[:job_id])
    @resume = Resume.new
  end

  def create
    @job = Job.find(params[:job_id])
    @resume = Resume.new(resume_params)
    @resume.job = @job
    @resume.user = current_user
    if @resume.save
      redirect_to job_path(@job), notice: "Resume submitted"
    else
      render :new
    end
  end


  private

  def resume_params
    params.require(:resume).permit(:content, :attachment)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    flash[:notice] = "hiiiiiiii"
  end

end

app/helpers/admin/jobs_helper.rb
module Admin::JobsHelper
end

app/helpers/admin/resumes_helper.rb
module Admin::ResumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

 def resource
   @resource ||= User.new
 end

 def resource_class
   User
 end

 def devise_mapping
   @devise_mapping ||= Devise.mappings[:user]
 end
 
end

app/helpers/flashes_helper.rb
module FlashesHelper

  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning" }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice "alert", "notice", "warning"
  end


end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_status(job)
    if job.is_hidden
      content_tag(:span, "", :class => "fa fa-lock fa-2x")
    else
      content_tag(:span, "", :class => "fa fa-globe fa-2x")
    end
  end

end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/jobs/_form.html.erb
<%= simple_form_for [:admin, @job] do |f| %>

    <%= f.input :title, input_html: { class: "form-control" } %>
    <%= f.input :description, input_html: { class: "form-control" }  %>
    <%= f.input :wage_lower_bound %>
    <%= f.input :wage_upper_bound %>
    <%= f.input :contact_email %>
    <%= f.input :is_hidden %>

   <%= f.submit "Submit", data: { disable_with: "Submiting...." }, class:" btn btn-primary" %>

<% end %>

app/views/admin/jobs/edit.html.erb
<h1 class="text-center"> </h1>

<div class="col-md-4 col-md-offset-4">

  <%= render "form" %>

</div>

app/views/admin/jobs/index.html.erb
<div class="admin-job">
  <%= link_to("Publish a job", new_admin_job_path, class:"btn btn-primary pull-right") %>
</div>

<table class="table table-boldered table-striped custab">
  <thead>
      <tr>
          <th> # </th>
          <th> Title </th>
          <th> Description </th>
          <th> Resume Received </th>
          <th> Wage Lower Bound </th>
          <th> Wage Upper Bound </th>
          <th> Option </th>
      </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
          <td> <%= job.id %> </td>
          <td>
            <%= render_job_status(job) %>
            <%= link_to(job.title, admin_job_path(job)) %> </td>
          <td> <%= job.description %> </td>
          <td> <%= link_to(job.resumes.count, admin_job_resumes_path(job)) %> </td>
          <td> <%= job.wage_lower_bound %> </td>
          <td> <%= job.wage_upper_bound %> </td>
          <td> <%= link_to "Edit job", edit_admin_job_path(job), class:"btn btn-sm btn-info" %>
               <%= link_to("Delete", admin_job_path(job), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-sm btn-danger") %>
               <% if job.is_hidden %>
                 <%= link_to("Publish", publish_admin_job_path(job), method: :post, class:"btn btn-sm btn-success") %>
               <% else %>
                 <%= link_to("Hide", hide_admin_job_path(job), method: :post, class:"btn btn-sm btn-warning") %>
               <% end %>
          </td>
      </tr>
    <% end %>

  </tbody>

</table>

app/views/admin/jobs/new.html.erb
<h1 class="text-center"> Publish a job</h1>

  <div class="col-md-4 col-md-offset-4">

    <%= render "form" %>

  </div>

app/views/admin/resumes/_resumes.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-md-12">
        <h3 class="panel-title">
        <%= resume.user.email %>
        </h3>
      </div>
    </div>
  </div>

  <div class="panel panel-body">

      <div class="col-md-12">
        <%= simple_format(resume.content) %>
      </div>
      <hr>
      <% if resume.attachment.present? %>
        <i class="fa fa-paperclip">
          <%= link_to("Download Resume", resume.attachment_url) %>
        </i>
      <% else %>
          No Attachment
      <% end %>
  </div>

</div>

app/views/admin/resumes/index.html.erb
<h1> <%= @job.title %> - Resumes Lists</h1>

<hr>

  <%= render :partial => "resumes", :collection => @resumes, :as => :resume %>

</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %> ">
      <button class="close" data-dismiss="alert"> X </button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top:100px;" %>
  <p class="text-center">
    Copyright ©2017
    <br> Design by <a href="#" target=_blank> Justin Ng </a>
  </p>

</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
      <div class="navbar-header">
          <a class="navbar-brand" href="/"><i class="fa fa-diamond" aria-hidden="true">真·24K Offer</i></a>
      </div>

      <div class="collapse navbar-collapse ">
        <ul class="nav navbar-nav navbar-right">
            <% if !current_user %>
                <li><a href="#" data-toggle="modal" data-target="#signup-modal">注册</a></li>
                <li><a href="#" data-toggle="modal" data-target="#login-modal">登入</a></li>
            <% else %>
              <li class="dropdown">
                <a href="#", class="dropdown-toggle" data-toggle="dropdown">
                  Hi!, <%= current_user.email %>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <% if current_user.is_admin? %>
                      <li> <%= link_to "Admin Panel", admin_jobs_path %></li>
                  <% end %>
                      <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            <% end %>
          </ul>

      </div>
  </div>
</nav>



<!-- 以下代码添加在最后 -->
<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog" role="document">
	<div class="loginmodal-container">
	   <h2>Log in</h2>
	   <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
		 <div class="form-inputs">
		   <%= f.input :email, required: false, autofocus: true %>
		   <%= f.input :password, required: false %>
		   <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
		 </div>
		 <div class="form-actions">
		   <%= f.button :submit, "Log in" %>
		 </div>
	   <% end %>
	</div>
  </div>
</div>

<div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
	<div class="loginmodal-container">
	  <h2>Sign up</h2>
		<%= simple_form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
		<%= f.error_notification %>
		<div class="form-inputs">
		  <%= f.input :email, required: true, autofocus: true %>
		  <%= f.input :password, required: true, hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length) %>
		  <%= f.input :password_confirmation, required: true %>
		</div>
		<div class="form-actions">
			<%= f.button :submit, "Sign up" %>
		</div>
	  <% end %>
	</div>
  </div>
</div>

app/views/jobs/_form.html.erb
<%= simple_form_for @job do |f| %>

    <%= f.input :title, input_html: { class: "form-control" } %>
    <%= f.input :description, input_html: { class: "form-control" }  %>
    <%= f.input :wage_lower_bound %>
    <%= f.input :wage_upper_bound %>
    <%= f.input :contact_email %>
    <%= f.input :is_hidden %>

   <%= f.submit "Submit", data: { disable_with: "Submiting...." }, class:" btn btn-primary" %>

<% end %>

app/views/jobs/edit.html.erb
<h1 class="text-center"> Edit Job </h1>

<div class="col-md-4 col-md-offset-4">

  <%= render  "form" %>

</div>

app/views/jobs/index.html.erb
<div class="dropdown pull-right">
  <button class="dropdown btn btn-sm btn-default" data-toggle="dropdown">
    <span href="#"> Filter by
      <b class="caret"></b>
    </span>
  </button>
    <ul class="dropdown-menu">
      <li> <%= link_to("By lower bound", jobs_path(:order => "by_lower_bound")) %> </li>
      <li> <%= link_to("By upper bound", jobs_path(:order => "by_upper_bound")) %> </li>
      <li> <%= link_to("Latest publish", jobs_path) %></li>
    </ul>

</div>

<table class="table table-hover">
  <thead>
      <tr>
          <th> # </th>
          <th> Title </th>
          <th> Wage Lower Bound </th>
          <th> Wage Upper Bound </th>
          <th> Last Update </th>
      </tr>
  </thead>

  <tbody>
      <% @jobs.each do |job| %>
        <tr>
            <td> <%= job.id %> </td>
            <td>
              <%= link_to(job.title, job_path(job)) %>
            </td>
            <td> <%= job.wage_lower_bound %> </td>
            <td> <%= job.wage_upper_bound %> </td>
            <td> <%= job.created_at %> </td>
        </tr>
      <% end %>
  </tbody>
</table>

app/views/jobs/new.html.erb
<h1 class="text-center"> Add a job</h1>

  <div class="col-md-4 col-md-offset-4">

    <%= render  "form" %>

  </div>

app/views/jobs/show.html.erb
<h1> <%= @job.title %> </h1>

<div class="text-center">
  <%= link_to("Submit Resume",new_job_resume_path(@job), style:"font-size: 30px; text-decoration:underline;") %>

</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing10</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container-fluid">
          <%= render "common/navbar" %>
          <%= render "common/flashes" %>
            <div class="row">
                <div class="col-md-2">
                  <ul class="nav nav-pills nav-stacked" style="max-with: 300px; padding-top: 20px;">
                    <li class="active"> <%= link_to("Jobs", admin_jobs_path) %></li>
                  </ul>
                </div>

                <div class="col-md-10">
                  <%= yield %>
                </div>
            </div>

        </div>
          <%= render "common/footer" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobListing10</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <div class="container-fluid">
          <div class="row">
            <%= render "common/navbar" %>
          </div>

          <%= render "common/flashes" %>
          <%= yield %>
        </div>
          <%= render "common/footer" %>
  </body>
</html>

app/views/resumes/new.html.erb
<h3> Submit Resume to <%= @job.title %> </h3>

  <%= simple_form_for [@job, @resume] do |f| %>

    <%= f.input :content %>
    <%= f.input :attachment %>
    
    <%= f.submit "Submit", disable_with: "Submitting", class:"btn btn-primary" %>

  <% end %>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <h1 class="title">18K Offer</h1>
    <p class="slogan">18K Offer 是一个提供18K薪水工作机会的求职网站。
    <br>
    我们希望藉由这个网站，能让大家找到且应征上高薪且优质的工作。
    <br>
 	凭借自己的努力和天份也会变 Winner
    </p>
    <p class="lead"><a class="btn btn-lg btn-danger" href="/jobs">马上应征</a></p>
  </div>


<!-- body -->
  <section id="company">
    <div class = "container-fluid">
  	<div class="row">
  	  <div class="col-sm-4 ">
  		<div class="thumbnail">
  		  <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-43-31.png" alt="search" class = "img-thumbnail">
  		  <div class="caption">
  			<h3>北京朝阳建外SOHO</h3>
  		  </div>
  		</div>
  	  </div>
  	  <div class="col-sm-4 ">
  		<div class="thumbnail">
  		  <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-43-48.png" alt="bid" class = "img-thumbnail">
  		  <div class="caption">
  			<h3>info@18koffer.com</h3>
  		  </div>
  		</div>
  	  </div>
  	  <div class="col-sm-4 ">
  		<div class="thumbnail">
  		  <img src="http://fullstack-public.oss-cn-qingdao.aliyuncs.com/2017-04-15-Screenshot%20at%20Apr%2015%2021-44-00.png" alt="heart" class = "img-thumbnail">
  		  <div class="caption">
  			<h3>010-12344321</h3>
  		  </div>
  		</div>
  	  </div>
  	</div>
    </div>
  </section>

<!-- body. end>